// GENERATED by packages/authz/src/generate.ts - do not edit.
// Source: docs/authz/capability-matrix.yaml v2
import type { Role } from './roles.js';

/** Actions each role can hold under SOME condition - the UI gates on
 * these; the server decides per resource via the engine. */
export const ROLE_CAPABILITIES: Record<Role, readonly string[]> = {
  "patient": [
    "patient_identity.view",
    "patient_identity.update_contact_details",
    "patient_clinical_profile.view",
    "care_relationship.view",
    "treatment.view",
    "activity.view",
    "survey_assignment.view",
    "survey_response.view",
    "survey_response.save_draft",
    "survey_response.submit",
    "survey_response.view_trend",
    "message_thread.view",
    "message_thread.post",
    "attachment.upload",
    "attachment.download",
    "value_entry.view",
    "value_entry.create",
    "symptom_observation.view",
    "symptom_observation.create",
    "audit_log.view_own_access_history",
    "own_settings.view",
    "own_settings.update",
    "own_data_export.request",
    "own_data_export.download"
  ],
  "treatment_member": [
    "patient_identity.view",
    "patient_identity.update_contact_details",
    "patient_clinical_profile.view",
    "care_relationship.view",
    "care_relationship.create",
    "care_relationship.end",
    "treatment.view",
    "treatment.update",
    "treatment.enrol_patient",
    "treatment.enter_on_behalf_of_patient",
    "treatment_template.view",
    "activity.view",
    "activity.create",
    "activity.update",
    "activity.cancel",
    "task.view",
    "task.create",
    "task.claim",
    "task.assign_to_other",
    "task.complete",
    "survey_template.view",
    "survey_assignment.view",
    "survey_assignment.create",
    "survey_assignment.schedule_recurring",
    "survey_assignment.cancel",
    "survey_assignment.send_reminder",
    "survey_response.view",
    "survey_response.submit_on_behalf_of_patient",
    "survey_response.view_trend",
    "alert.view",
    "alert.view_evaluation_trace",
    "alert.acknowledge",
    "alert.assign",
    "alert.comment",
    "alert.resolve",
    "message_thread.view",
    "message_thread.post",
    "internal_note.view",
    "internal_note.post",
    "attachment.upload",
    "attachment.download",
    "value_entry.view",
    "value_entry.create",
    "symptom_observation.view",
    "symptom_observation.create",
    "symptom_taxonomy.view",
    "patient_data_export.request",
    "patient_data_export.download",
    "staff_account.view",
    "team.view",
    "audit_log.view_own_access_history",
    "report.view",
    "own_settings.view",
    "own_settings.update",
    "own_data_export.request",
    "own_data_export.download"
  ],
  "treatment_lead": [
    "patient_identity.view",
    "patient_identity.update_contact_details",
    "patient_clinical_profile.view",
    "care_relationship.view",
    "care_relationship.create",
    "care_relationship.end",
    "treatment.view",
    "treatment.create",
    "treatment.update",
    "treatment.change_lifecycle_state",
    "treatment.manage_team",
    "treatment.enrol_patient",
    "treatment.enter_on_behalf_of_patient",
    "treatment.configure_program_rules",
    "treatment_template.view",
    "treatment_template.create",
    "treatment_template.update_draft",
    "treatment_template.publish",
    "treatment_template.archive",
    "activity.view",
    "activity.create",
    "activity.update",
    "activity.cancel",
    "task.view",
    "task.create",
    "task.claim",
    "task.assign_to_other",
    "task.complete",
    "survey_template.view",
    "survey_template.create",
    "survey_template.update_draft",
    "survey_template.publish",
    "survey_template.archive",
    "survey_template.configure_alert_rules",
    "survey_assignment.view",
    "survey_assignment.create",
    "survey_assignment.schedule_recurring",
    "survey_assignment.cancel",
    "survey_assignment.send_reminder",
    "survey_response.view",
    "survey_response.submit_on_behalf_of_patient",
    "survey_response.view_trend",
    "alert.view",
    "alert.view_evaluation_trace",
    "alert.acknowledge",
    "alert.assign",
    "alert.comment",
    "alert.resolve",
    "message_thread.view",
    "message_thread.post",
    "internal_note.view",
    "internal_note.post",
    "attachment.upload",
    "attachment.download",
    "value_entry.view",
    "value_entry.create",
    "symptom_observation.view",
    "symptom_observation.create",
    "symptom_taxonomy.view",
    "symptom_taxonomy.manage",
    "patient_data_export.request",
    "patient_data_export.download",
    "staff_account.view",
    "patient_account.create",
    "team.view",
    "team.create",
    "team.update_membership",
    "audit_log.view_own_access_history",
    "report.view",
    "own_settings.view",
    "own_settings.update",
    "own_data_export.request",
    "own_data_export.download"
  ],
  "administrator": [
    "patient_identity.view",
    "patient_identity.update_contact_details",
    "staff_account.view",
    "staff_account.create",
    "staff_account.deactivate",
    "staff_account.reset_credentials",
    "patient_account.create",
    "patient_account.deactivate",
    "patient_account.reset_credentials",
    "team.view",
    "team.create",
    "team.update_membership",
    "audit_log.view_own_access_history",
    "audit_log.view_full",
    "own_settings.view",
    "own_settings.update",
    "own_data_export.request",
    "own_data_export.download"
  ]
};

/** Slice attributes the generated schema declares per resource type -
 * the engine drops anything else before evaluation. */
export const RESOURCE_ATTRS: Record<string, readonly string[]> = {
  "patient_identity": [
    "careTeam",
    "subjectUser"
  ],
  "patient_clinical_profile": [
    "careTeam",
    "subjectUser"
  ],
  "care_relationship": [
    "subjectUser",
    "team"
  ],
  "treatment": [
    "leads",
    "subjectUser",
    "team"
  ],
  "treatment_template": [],
  "activity": [
    "subjectUser",
    "team"
  ],
  "task": [
    "ownerUser",
    "team"
  ],
  "survey_template": [],
  "survey_assignment": [
    "subjectUser",
    "team"
  ],
  "survey_response": [
    "careTeam",
    "subjectUser"
  ],
  "alert": [
    "team"
  ],
  "message_thread": [
    "subjectUser",
    "team"
  ],
  "internal_note": [
    "team"
  ],
  "attachment": [
    "careTeam",
    "subjectUser",
    "team"
  ],
  "value_entry": [
    "careTeam",
    "subjectUser"
  ],
  "symptom_observation": [
    "careTeam",
    "subjectUser"
  ],
  "symptom_taxonomy": [],
  "patient_data_export": [
    "careTeam"
  ],
  "staff_account": [],
  "patient_account": [],
  "team": [],
  "audit_log": [
    "subjectUser"
  ],
  "report": [
    "team"
  ],
  "own_settings": [
    "subjectUser"
  ],
  "own_data_export": [
    "subjectUser"
  ]
};

/** role:scope action groups with no member action in the matrix - their
 * pattern policies can never apply, which validation must excuse. */
export const EMPTY_GROUPS: readonly string[] = [
  "grp:patient:own",
  "grp:patient:care_relationship",
  "grp:patient:team_member",
  "grp:patient:team_lead",
  "grp:patient:any",
  "grp:treatment_member:team_lead",
  "grp:treatment_lead:own",
  "grp:administrator:own",
  "grp:administrator:care_relationship",
  "grp:administrator:team_member",
  "grp:administrator:team_lead"
];

export const ACTION_METADATA: Record<string, { audit: 'always' | 'never'; patientScoped: boolean }> = {
  "patient_identity.view": {
    "audit": "always",
    "patientScoped": true
  },
  "patient_identity.update_contact_details": {
    "audit": "always",
    "patientScoped": true
  },
  "patient_clinical_profile.view": {
    "audit": "always",
    "patientScoped": true
  },
  "care_relationship.view": {
    "audit": "always",
    "patientScoped": true
  },
  "care_relationship.create": {
    "audit": "always",
    "patientScoped": true
  },
  "care_relationship.end": {
    "audit": "always",
    "patientScoped": true
  },
  "treatment.view": {
    "audit": "always",
    "patientScoped": true
  },
  "treatment.create": {
    "audit": "always",
    "patientScoped": true
  },
  "treatment.update": {
    "audit": "always",
    "patientScoped": true
  },
  "treatment.change_lifecycle_state": {
    "audit": "always",
    "patientScoped": true
  },
  "treatment.manage_team": {
    "audit": "always",
    "patientScoped": true
  },
  "treatment.enrol_patient": {
    "audit": "always",
    "patientScoped": true
  },
  "treatment.enter_on_behalf_of_patient": {
    "audit": "always",
    "patientScoped": true
  },
  "treatment.configure_program_rules": {
    "audit": "always",
    "patientScoped": true
  },
  "treatment_template.view": {
    "audit": "never",
    "patientScoped": false
  },
  "treatment_template.create": {
    "audit": "always",
    "patientScoped": false
  },
  "treatment_template.update_draft": {
    "audit": "always",
    "patientScoped": false
  },
  "treatment_template.publish": {
    "audit": "always",
    "patientScoped": false
  },
  "treatment_template.archive": {
    "audit": "always",
    "patientScoped": false
  },
  "activity.view": {
    "audit": "always",
    "patientScoped": true
  },
  "activity.create": {
    "audit": "always",
    "patientScoped": true
  },
  "activity.update": {
    "audit": "always",
    "patientScoped": true
  },
  "activity.cancel": {
    "audit": "always",
    "patientScoped": true
  },
  "task.view": {
    "audit": "always",
    "patientScoped": true
  },
  "task.create": {
    "audit": "never",
    "patientScoped": true
  },
  "task.claim": {
    "audit": "never",
    "patientScoped": true
  },
  "task.assign_to_other": {
    "audit": "never",
    "patientScoped": true
  },
  "task.complete": {
    "audit": "never",
    "patientScoped": true
  },
  "survey_template.view": {
    "audit": "never",
    "patientScoped": false
  },
  "survey_template.create": {
    "audit": "always",
    "patientScoped": false
  },
  "survey_template.update_draft": {
    "audit": "always",
    "patientScoped": false
  },
  "survey_template.publish": {
    "audit": "always",
    "patientScoped": false
  },
  "survey_template.archive": {
    "audit": "always",
    "patientScoped": false
  },
  "survey_template.configure_alert_rules": {
    "audit": "always",
    "patientScoped": false
  },
  "survey_assignment.view": {
    "audit": "always",
    "patientScoped": true
  },
  "survey_assignment.create": {
    "audit": "always",
    "patientScoped": true
  },
  "survey_assignment.schedule_recurring": {
    "audit": "always",
    "patientScoped": true
  },
  "survey_assignment.cancel": {
    "audit": "always",
    "patientScoped": true
  },
  "survey_assignment.send_reminder": {
    "audit": "never",
    "patientScoped": true
  },
  "survey_response.view": {
    "audit": "always",
    "patientScoped": true
  },
  "survey_response.save_draft": {
    "audit": "never",
    "patientScoped": true
  },
  "survey_response.submit": {
    "audit": "always",
    "patientScoped": true
  },
  "survey_response.submit_on_behalf_of_patient": {
    "audit": "always",
    "patientScoped": true
  },
  "survey_response.view_trend": {
    "audit": "always",
    "patientScoped": true
  },
  "alert.view": {
    "audit": "always",
    "patientScoped": true
  },
  "alert.view_evaluation_trace": {
    "audit": "always",
    "patientScoped": true
  },
  "alert.acknowledge": {
    "audit": "always",
    "patientScoped": true
  },
  "alert.assign": {
    "audit": "always",
    "patientScoped": true
  },
  "alert.comment": {
    "audit": "always",
    "patientScoped": true
  },
  "alert.resolve": {
    "audit": "always",
    "patientScoped": true
  },
  "message_thread.view": {
    "audit": "always",
    "patientScoped": true
  },
  "message_thread.post": {
    "audit": "always",
    "patientScoped": true
  },
  "internal_note.view": {
    "audit": "always",
    "patientScoped": true
  },
  "internal_note.post": {
    "audit": "always",
    "patientScoped": true
  },
  "attachment.upload": {
    "audit": "always",
    "patientScoped": true
  },
  "attachment.download": {
    "audit": "always",
    "patientScoped": true
  },
  "value_entry.view": {
    "audit": "always",
    "patientScoped": true
  },
  "value_entry.create": {
    "audit": "always",
    "patientScoped": true
  },
  "symptom_observation.view": {
    "audit": "always",
    "patientScoped": true
  },
  "symptom_observation.create": {
    "audit": "always",
    "patientScoped": true
  },
  "symptom_taxonomy.view": {
    "audit": "never",
    "patientScoped": false
  },
  "symptom_taxonomy.manage": {
    "audit": "always",
    "patientScoped": false
  },
  "patient_data_export.request": {
    "audit": "always",
    "patientScoped": true
  },
  "patient_data_export.download": {
    "audit": "always",
    "patientScoped": true
  },
  "staff_account.view": {
    "audit": "always",
    "patientScoped": false
  },
  "staff_account.create": {
    "audit": "always",
    "patientScoped": false
  },
  "staff_account.deactivate": {
    "audit": "always",
    "patientScoped": false
  },
  "staff_account.reset_credentials": {
    "audit": "always",
    "patientScoped": false
  },
  "patient_account.create": {
    "audit": "always",
    "patientScoped": true
  },
  "patient_account.deactivate": {
    "audit": "always",
    "patientScoped": true
  },
  "patient_account.reset_credentials": {
    "audit": "always",
    "patientScoped": true
  },
  "team.view": {
    "audit": "never",
    "patientScoped": false
  },
  "team.create": {
    "audit": "always",
    "patientScoped": false
  },
  "team.update_membership": {
    "audit": "always",
    "patientScoped": false
  },
  "audit_log.view_own_access_history": {
    "audit": "never",
    "patientScoped": false
  },
  "audit_log.view_full": {
    "audit": "always",
    "patientScoped": false
  },
  "report.view": {
    "audit": "always",
    "patientScoped": false
  },
  "own_settings.view": {
    "audit": "never",
    "patientScoped": false
  },
  "own_settings.update": {
    "audit": "always",
    "patientScoped": false
  },
  "own_data_export.request": {
    "audit": "always",
    "patientScoped": false
  },
  "own_data_export.download": {
    "audit": "always",
    "patientScoped": false
  }
};
