import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ROLES } from './roles.js';
import { attrsForResource, generateSchema, actionId, groupId } from './cedar.js';
import { checkInvariants, defaultMatrixPath, grantCount, loadMatrix } from './matrix.js';

/**
 * The capability-matrix generator (ADR-0006). One source of truth in
 * docs/authz/capability-matrix.yaml; three generated artifacts, checked in
 * and drift-checked by CI (`generate.ts --check`):
 *
 *  1. cedar-schema.generated.ts - entity types, actions, role:scope groups;
 *  2. capabilities.generated.ts - UI capability flags + audit metadata;
 *  3. docs/authz/matrix.generated.md - the human-readable matrix for the
 *     compliance pack.
 */

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, '..', '..', '..');

interface Artifact {
  filePath: string;
  content: string;
}

export function generateArtifacts(): Artifact[] {
  const matrixPath = defaultMatrixPath(REPO_ROOT);
  const matrix = loadMatrix(matrixPath);

  const violations = checkInvariants(matrix);
  if (violations.length > 0) {
    const lines = violations.map((v) => `  ${v.invariant}: ${v.detail}`).join('\n');
    throw new Error(`Capability matrix violates its invariants:\n${lines}`);
  }

  const schemaTs =
    '// GENERATED by packages/authz/src/generate.ts - do not edit.\n' +
    `// Source: docs/authz/capability-matrix.yaml v${matrix.version}\n\n` +
    `export const CEDAR_SCHEMA: string = ${JSON.stringify(generateSchema(matrix))};\n`;

  const capabilities: Record<string, string[]> = Object.fromEntries(ROLES.map((r) => [r, []]));
  const metadata: Record<string, { audit: 'always' | 'never'; patientScoped: boolean }> = {};
  const actionGroups: Record<string, string[]> = {};
  const populatedGroups = new Set<string>();
  for (const resource of matrix.resources) {
    for (const action of resource.actions) {
      const id = actionId(resource.id, action.id);
      metadata[id] = { audit: action.audit, patientScoped: resource.patientScoped };
      actionGroups[id] = [];
      for (const role of ROLES) {
        const scope = action.grants[role];
        if (scope !== 'deny') {
          (capabilities[role] as string[]).push(id);
          (actionGroups[id] as string[]).push(groupId(role, scope));
          populatedGroups.add(groupId(role, scope));
        }
      }
    }
  }
  const emptyGroups = ROLES.flatMap((role) =>
    (['self', 'own', 'care_relationship', 'team_member', 'team_lead', 'any'] as const)
      .map((scope) => groupId(role, scope))
      .filter((g) => !populatedGroups.has(g)),
  );
  const resourceAttrs = Object.fromEntries(
    matrix.resources.map((r) => [r.id, attrsForResource(matrix, r.id).map((a) => a.name)]),
  );

  const capsTs =
    '// GENERATED by packages/authz/src/generate.ts - do not edit.\n' +
    `// Source: docs/authz/capability-matrix.yaml v${matrix.version}\n` +
    "import type { Role } from './roles.js';\n\n" +
    '/** Actions each role can hold under SOME condition - the UI gates on\n' +
    ' * these; the server decides per resource via the engine. */\n' +
    `export const ROLE_CAPABILITIES: Record<Role, readonly string[]> = ${JSON.stringify(
      capabilities,
      null,
      2,
    )};\n\n` +
    '/** Slice attributes the generated schema declares per resource type -\n' +
    ' * the engine drops anything else before evaluation. */\n' +
    `export const RESOURCE_ATTRS: Record<string, readonly string[]> = ${JSON.stringify(
      resourceAttrs,
      null,
      2,
    )};\n\n` +
    '/** role:scope action groups with no member action in the matrix - their\n' +
    ' * pattern policies can never apply, which validation must excuse. */\n' +
    `export const EMPTY_GROUPS: readonly string[] = ${JSON.stringify(emptyGroups, null, 2)};\n\n` +
    '/** role:scope action-group membership per action - the engine supplies\n' +
    ' * these as action-entity parents so the hot path needs no schema. */\n' +
    `export const ACTION_GROUPS: Record<string, readonly string[]> = ${JSON.stringify(
      actionGroups,
      null,
      2,
    )};\n\n` +
    `export const ACTION_METADATA: Record<string, { audit: 'always' | 'never'; patientScoped: boolean }> = ${JSON.stringify(
      metadata,
      null,
      2,
    )};\n`;

  const md: string[] = [
    '# Capability matrix - generated view',
    '',
    '<!-- GENERATED by packages/authz/src/generate.ts from capability-matrix.yaml',
    '     - do not edit. Regenerate: pnpm --filter @mio/authz generate -->',
    '',
    `Source version ${matrix.version} - ${matrix.resources.length} resources, ` +
      `${grantCount(matrix)} explicit grants. A cell is the CONDITION under which`,
    'the action is permitted; `deny` means no path exists.',
    '',
    '| Resource.action | Audit | ' + ROLES.map((r) => r.replace('_', ' ')).join(' | ') + ' |',
    '|---|---|' + ROLES.map(() => '---').join('|') + '|',
  ];
  for (const resource of matrix.resources) {
    for (const action of resource.actions) {
      md.push(
        `| \`${actionId(resource.id, action.id)}\` | ${action.audit} | ` +
          ROLES.map((role) => {
            const scope = action.grants[role];
            return scope === 'deny' ? '·' : `**${scope.replace(/_/g, ' ')}**`;
          }).join(' | ') +
          ' |',
      );
    }
  }
  md.push('');

  return [
    { filePath: path.join(HERE, 'cedar-schema.generated.ts'), content: schemaTs },
    { filePath: path.join(HERE, 'capabilities.generated.ts'), content: capsTs },
    {
      filePath: path.join(REPO_ROOT, 'docs', 'authz', 'matrix.generated.md'),
      content: md.join('\n'),
    },
  ];
}

function main(): void {
  const check = process.argv.includes('--check');
  const artifacts = generateArtifacts();
  let drifted = false;
  for (const artifact of artifacts) {
    if (check) {
      let existing = '';
      try {
        existing = readFileSync(artifact.filePath, 'utf8');
      } catch {
        /* missing counts as drift */
      }
      if (existing !== artifact.content) {
        drifted = true;
        console.error(`DRIFT: ${path.relative(REPO_ROOT, artifact.filePath)} is stale`);
      }
    } else {
      mkdirSync(path.dirname(artifact.filePath), { recursive: true });
      writeFileSync(artifact.filePath, artifact.content);
      console.error(`wrote ${path.relative(REPO_ROOT, artifact.filePath)}`);
    }
  }
  if (check && drifted) {
    console.error('Regenerate with: pnpm --filter @mio/authz generate');
    process.exit(1);
  }
  if (check) {
    console.error('generated artifacts are fresh');
  }
}

const invokedDirectly =
  process.argv[1] !== undefined &&
  import.meta.url === new URL(`file://${path.resolve(process.argv[1])}`).href;
if (invokedDirectly) {
  main();
}
